[package]
name = "keylog"
version = "0.1.0"
edition = "2024"

[dependencies]
termion = "*"
libc = "0.2"
crossterm = "0.27"
rustix = { version = "1", default-features = false, features = ["std", "stdio", "termios"] }